
service: static-site-mailer

functions:
  staticSiteMailer:
    handler: handler.staticSiteMailer
  events:
    http:
      method: post
      path: static-site-mailer
      cors: true
    handler: handler.staticSiteMailer

provider:
  name: aws
  runtime: nodejs6.10
iamRoleStatements: # IAM role statements so that services can be accessed in the AWS account
    - Effect: 'Allow'
      Action: 
        - "ses:*"
      Resource: "*"
  
